<CLevel>
   	<CEntity>
        <vPosition fX="0" fY="0" />
        <fRotation value="0" />
        <sFilePath value="resources/maps/map.ed" />
   	</CEntity>
	<CEntity>
        <vPosition fX="400" fY="225" />
        <fRotation value="0" />
        <sFilePath value="resources/orkito/orkito.ed" />
     </CEntity>
	<CEntity>
        <vPosition fX="400" fY="180" />
        <fRotation value="0" />
        <sFilePath value="resources/campfire/campfire.ed" />
    </CEntity>
</CLevel>
